INSERT INTO branch (name, full_name, code) VALUES
('Acquisition Corps', 'Acquisition Corps', 'AC'),
('Adjutant General''s Corps', 'Adjutant General''s Corps', 'AG'),
('Air Defense Artillery', 'Air Defense Artillery', 'AD'),
('Armor','Armor Branch','AR'),
('Aviation', 'Aviation', 'AV'),
('Army Bands', 'Army Bands', NULL),
('Chemical Corps', 'Chemical Corps', 'CM'),
('Civil Affairs', 'Civil Affairs Corps', 'CA'),
('Cyber', 'Cyber Warfare', 'CY'),
('Electronic Warfare', 'Electronic Warfare', 'EW'),
('Engineers', 'Corps of Engineers', 'EN'),
('Field Artillery', 'Field Artillery', 'FA'),
('Finance', 'Finance Corps', 'FI'),
('General Staff', 'General Staff', 'GS'),
('Infantry', 'Infantry', 'IN'),
('Inspector General', 'Inspector General', 'IG'),
('Judge Advocate General''s Corps', 'Judge Advocate General''s Corps', 'JA'),
('Logistics', 'Logistics', 'LG'),
('Medical', 'Medical Corps', 'MC'),
('Medical Service', 'Medical Service Corps', 'MS'),
('Dental', 'Dental Corps', 'DC'),
('Veterinary', 'Veterinary Corps', 'VC'),
('Medical Specialist', 'Medical Specialist Corps', 'SP'),
('Nurse Corps', 'Nurse Corps', 'AN'),
('Military Intelligence', 'Military Intelligence Corps', 'MI'),
('Military Police', 'Military Police Corps', 'MP'),
('National Guard', 'National Guard Bureau', 'NG'),
('Ordnance Corps', 'Ordnance Corps', 'OD'),
('Psychological Operations', 'Psychological Operations', NULL),
('Public Affairs', 'Public Affairs', 'PA'),
('Quartermaster', 'Quartermaster Corps', 'QM'),
('Signal', 'Signal Corps', 'SC'),
('Special Forces', 'Special Forces', 'SF'),
('Staff Specialist USAR/ARNG', 'Staff Specialist USAR/ARNG', 'SS'),
('Transportation Corps', 'Transportation Corps', 'TC'),
('Chaplain Corps', 'Chaplain Corps', 'CH');
